orbs:
  aws-cli: circleci/aws-cli@2.1.0

jobs:
  build_deploy:
    docker:
      # replace with your preferred image
      - image: cimg/node:17.7.1 
    steps:
      - aws-cli/setup:
          aws-region: us-east-1 
          aws-secret-access-key: hM3H+oB6lXmip9GjBbZODNwffl3oV4maDGY0+u3A 
          configure-profile-region: true 
          disable-aws-pager: true 
          profile-name: docker-react 
          version: '2.1' 

workflows:
  example-workflow:
    jobs:
      - - aws-elastic-beanstalk/docker-react:
            app-dir: . 
            application-name: docker-react 
            description: Course hardcore mdf
            environment-name: docker-react-env 
            image: cimg/node:17.7.1 
            label: circleci-test 