orbs:
  aws-cli: circleci/aws-cli@2.1.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-cli/setup:
          aws-region: us-east-1 
          aws-secret-access-key: hM3H+oB6lXmip9GjBbZODNwffl3oV4maDGY0+u3A 
          configure-profile-region: true 
          disable-aws-pager: true 
          profile-name: docker-react 
          version: '2.1' 

workflows:
  example-workflow:
    jobs:
      - example-job