jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - github-cli/setup:
          hostname: codes4free/docker-react 
          token: CircleCI 
          version: '2.3' 

workflows:
  example-workflow:
    jobs:
      - example-job